apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdcal
  namespace: mdcal
spec:
  selector:
    matchLabels:
      app: mdcal
  replicas: 2
  template:
    metadata:
      labels:
        app: mdcal
    spec:
      containers:
      - name: mdcal
        image: yumekiti/mdcal:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mdcal
  namespace: mdcal
spec:
  selector:
    app: mdcal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mdcal
  namespace: mdcal
spec:
  ingressClassName: nginx
  rules:
  - host: mdcal.yumekiti.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mdcal
            port:
              number: 80